version: 2

updates:
  - directory: "/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
    reviewers:
      - "cdriesler"
    versioning-strategy: "increase"

  - directory: "/packages/converters"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-name: "Speckle*"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"

