version: 2

updates:
  - directory: "/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 5
    reviewers:
      - "cdriesler"

  - directory: "/packages/nodes"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 5
    reviewers:
      - "cdriesler"

  - directory: "/packages/converters"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-name: "Speckle*"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"

  - directory: "/apps/nodepen-client"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-name: "next"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"
