version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"

  - package-ecosystem: "npm"
    directory: "/packages/nodes"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"

  - package-ecosystem: "nuget"
    directory: "/packages/converters"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-name: "Speckle*"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"

  - package-ecosystem: "npm"
    directory: "/apps/nodepen-client"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-name: "next"
    open-pull-requests-limit: 1
    reviewers:
      - "cdriesler"
