apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-bq-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: np-bq-io
  template:
    metadata:
      labels:
        app: np-bq-io
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: np-bq-io
          image: gcr.io/{{ .Values.projectId }}/np-bq-io:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9600
          env:
            - name: NP_GLOBAL_PREFIX
              value: "{{ .Values.globalPrefix }}"
            - name: NP_DB_HOST
              value: "{{ .Values.redisHost }}"
            - name: NP_DB_PORT
              value: "{{ .Values.redisPort }}"
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 750Mi
          volumeMounts:
            - mountPath: /temp-i
              name: io-temp
      volumes:
        - name: io-temp
          emptyDir: {}
