apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-bq-render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: np-bq-render
  template:
    metadata:
      labels:
        app: np-bq-render
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: np-prod-pool-rq
      containers:
        - name: np-bq-render
          image: gcr.io/{{ .Values.projectId }}/np-bq-render:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9700
          env:
            - name: NP_GLOBAL_PREFIX
              value: "{{ .Values.globalPrefix }}"
            - name: NP_DB_HOST
              value: "{{ .Values.redisHost }}"
            - name: NP_DB_PORT
              value: "{{ .Values.redisPort }}"
          resources:
            limits:
              cpu: 300m
              memory: 1.25Gi
              ephemeral-storage: 1Gi
            requests:
              cpu: 200m
              memory: 1Gi
              ephemeral-storage: 750Mi
          volumeMounts:
            - mountPath: /render/temp
              name: render-temp
      volumes:
        - name: render-temp
          emptyDir: {}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: np-rq-restart
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - "kubectl"
                - "rollout"
                - "restart"
                - "deployment/np-bq-render"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: np-render-restart
rules:
  - apiGroups: ["extensions", "apps"] # "" indicates the core API group
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-deployments
  namespace: default
subjects:
  - kind: Group
    name: system:serviceaccount
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: np-render-restart
  apiGroup: rbac.authorization.k8s.io
