name: test glasshopper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.14]

    steps:
    - uses: actions/checkout@v1
    - name: Initialize node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build for production
      run: npm run build
