name: build

on: [push]

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Build glib
        working-directory: ./lib
        run: |
          npm ci
          npm run build
      - name: Upload glib artifacts
        uses: actions/upload-artifact@master
        with:
          name: glib
          path: |
            lib/
            !lib/node_modules/
          retention-days: 1
  app:
    runs-on: ubuntu-latest
    needs: [lib]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Download glib artifacts
        uses: actions/download-artifact@v2
        with:
          name: glib
          path: app/glib/
      - name: Restore glib dependencies
        working-directory: ./app/glib
        run: npm ci
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.NODEPEN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.NODEPEN_GCP_TOKEN }}
          export_default_credentials: true
      - name: Setup GCR
        run: gcloud auth configure-docker
      - uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: gcr.io/${{ secrets.NODEPEN_GCP_PROJECT_ID }}/np-app:next
  api:
    runs-on: ubuntu-latest
    needs: [lib]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Download glib artifacts
        uses: actions/download-artifact@v2
        with:
          name: glib
          path: api/glib/
      - name: Restore glib dependencies
        working-directory: ./api/glib
        run: npm ci
      - name: Restore api secrets
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "auth.json"
          dir: "api/src/auth/"
          json: ${{ secrets.NODEPEN_API_SECRET_AUTH }}
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.NODEPEN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.NODEPEN_GCP_TOKEN }}
          export_default_credentials: true
      - name: Setup GCR
        run: gcloud auth configure-docker
      - uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: gcr.io/${{ secrets.NODEPEN_GCP_PROJECT_ID }}/np-api:next
  gh:compute:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.NODEPEN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.NODEPEN_GCP_TOKEN }}
          export_default_credentials: true
      - name: Setup GCR
        run: gcloud auth configure-docker
      - name: Build np-gh-compute
        run: |
          cd gh/compute
          docker build -t gcr.io/${{ secrets.NODEPEN_GCP_PROJECT_ID }}/np-gh-compute:next --build-arg NODEPEN_RHINO_TOKEN=${{ secrets.NODEPEN_RHINO_TOKEN }} .
          docker push gcr.io/${{ secrets.NODEPEN_GCP_PROJECT_ID }}/np-gh-compute:next
