on:
  push:
    branches:
      - "main"

name: cd

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Prepare glib
      working-directory: ./lib
      run: |
        npm ci
        npm run build

    - name: Install app dependencies
      working-directory: ./app
      run: npm ci

    - name: Build app
      working-directory: ./app
      run: npm run build

    - name: Install api dependencies
      working-directory: ./api
      run: npm ci

    - name: Build api
      working-directory: ./api
      run: npm run build

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Pretend to deploy
      run: echo "Deploying to production."