name: converters

on: [push]

jobs:
  build:
    name: build-converters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
          dotnet-quality: "ga"
      - name: Build project
        working-directory: packages/converters/
        run: dotnet build
