name: stage

on:
  workflow_dispatch:

env:
  GKE_CLUSTER: ${{ secrets.NODEPEN_GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.NODEPEN_GKE_ZONE }}
  NP_PREFIX: prod
  NP_TAG: next

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.NODEPEN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.NODEPEN_GCP_TOKEN }}
          export_default_credentials: true
      - name: Deploy np-dev-app
        run: |
          gcloud run deploy np-dev-app \
            --image=gcr.io/${{ secrets.NODEPEN_GCP_PROJECT_ID }}/np-app:next \
            --region=${{ secrets.NODEPEN_GCP_REGION }} \
            --set-env-vars=NEXT_PUBLIC_NP_API_ENDPOINT=https://api.dev.nodepen.io/graphql \
            --allow-unauthenticated
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.NODEPEN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.NODEPEN_GCP_TOKEN }}
          export_default_credentials: true
      - name: Deploy np-dev-api
        run: |
          gcloud run deploy np-dev-api \
            --image=gcr.io/${{ secrets.NODEPEN_GCP_PROJECT_ID }}/np-api:next \
            --region=${{ secrets.NODEPEN_GCP_REGION }} \
            --set-env-vars=NP_API_PORT=8080,NP_GLOBAL_PREFIX="$NP_PREFIX",NP_DB_HOST=${{ secrets.NODEPEN_REDIS_HOST }},NP_DB_PORT=${{ secrets.NODEPEN_REDIS_PORT }} \
            --allow-unauthenticated
  deploy-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.NODEPEN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.NODEPEN_GCP_TOKEN }}
          export_default_credentials: true
      - uses: azure/setup-helm@v1
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy
        run: |
          helm upgrade np-prod ./.charts/np-prod --namespace=default \
            --set=app.name=np-prod \
            --set=app.version=${{ github.sha }} \
            --set=redisHost=${{ secrets.NODEPEN_REDIS_HOST }} \
            --set=redisPort=${{ secrets.NODEPEN_REDIS_PORT }} \
            --set=projectId=${{ secrets.NODEPEN_GCP_PROJECT_ID }} \
            --set=tag="$NP_TAG" \
            --install
